"""add productos tables

Revision ID: 5fb466c177a6
Revises: 006_add_ingredientes_table
Create Date: 2026-05-11 16:41:26.539720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb466c177a6'
down_revision: Union[str, None] = '006_add_ingredientes_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_base', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('stock_cantidad', sa.Integer(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('imagen', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_disponible'), 'productos', ['disponible'], unique=False)
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=False)
    op.create_table('productos_categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_categorias_categoria_id'), 'productos_categorias', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_productos_categorias_producto_id'), 'productos_categorias', ['producto_id'], unique=False)
    op.create_table('productos_ingredientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('es_removible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_ingredientes_ingrediente_id'), 'productos_ingredientes', ['ingrediente_id'], unique=False)
    op.create_index(op.f('ix_productos_ingredientes_producto_id'), 'productos_ingredientes', ['producto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productos_ingredientes_producto_id'), table_name='productos_ingredientes')
    op.drop_index(op.f('ix_productos_ingredientes_ingrediente_id'), table_name='productos_ingredientes')
    op.drop_table('productos_ingredientes')
    op.drop_index(op.f('ix_productos_categorias_producto_id'), table_name='productos_categorias')
    op.drop_index(op.f('ix_productos_categorias_categoria_id'), table_name='productos_categorias')
    op.drop_table('productos_categorias')
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')
    op.drop_index(op.f('ix_productos_disponible'), table_name='productos')
    op.drop_table('productos')
    # ### end Alembic commands ###
